/*
Write a SQL query to find the total revenue generated by each genre in the year 2022.
Order by revenue DESC.

*/

select
	b.genre,
	sum(order_amount) as order_amount_by_genre
from
	big121.orders o
join big121.books b
on
	o.book_id = b.id
where
	extract (year
from
	order_date) = 2022
group by
	b.genre
order by
	order_amount_by_genre desc
; 