/*
Write a SQL query that returns the customer id, total revenue generated by the customer,
and the date of the first order placed by the customer, for customers who have placed orders.
Sort the results by total revenue in descending order.

*/

with cte as (
select
	customerid as cid,
	sum(priceperunit)
from
	big118.orders
group by
	customerid
)
select
	distinct cid,
	sum,
	order_date
from
	big118.orders o
join cte c on
	c.cid = o.customerid
order by
	order_date desc;


